### PR TITLE
adds version option

### PR DESCRIPTION
**Pull request by LucaSforza**
As requested in #66 I created the option to print the version on dbtc

### CODE REVIEW

**Comment by dpguthrie** [comment]
Thanks for opening this up @LucaSforza, I appreciate the contribution!  Couple of comments:

- I think `__version__` should exist in its own file - `_version.py`
- I'd like to investigate using this approach [here](https://github.com/python-poetry/poetry/issues/1036#issuecomment-489880822) to try and have a single place where version needs to be updated with `poetry version <version>`

**Comment by LucaSforza** [comment]
I added the function `version(__package__)` imported from module `importlib_metadata`,so I no longer use any global variables.

Now I should have solved the problem, tell me if everything is OK

**Comment by dpguthrie** [comment]
Thanks for making some of those changes.  Couple things that I'd like to see though:

- I think the `__version__` variable should be in its own `_verison.py` file next to `__init__.py`.
- This variable should be imported into `__init__.py` also so it's available to the python package as well.

Also, it looks like your last commit included some irrelevant files `.DSStore`.

**Comment by LucaSforza** [comment]
Ok i created the file `_version.py` with inside has the variable `__version__` ,please update me if everything is fine this time

**Comment by dpguthrie** [comment]
Could you remove the .DSStore file in this PR?

**Comment by LucaSforza** [comment]
Ok, sorry I didn't see that there were others left, now they should all have been deleted

**Pull request merged**
